apiVersion: v1
kind: Secret
metadata:
  name: vpsie-secret
  namespace: default
stringData:
  clientID: "7557aa5a-a1e6-11ed-9196-0050569c68dc"
  clientSecret: "REDACTED"
  datacenter: "ab70b3b6-9f22-11e3-8af5-005056aa8af7"
  url: "https://vpsie.com/api/v1"
  nodeid: "7be78c6f-db4e-11ed-8b5c-0050569c68dc"
  token: "REDACTED"
