apiVersion: v1
kind: Secret
metadata:
  name: vpsie-secret
  namespace: default
stringData:
  clientID: "65d10fc6-fb9b-11e3-b24c-005056aadd24"
  clientSecret: "cd4fde0dfe9ad5b51c09a21cfd2eba00ca09f5e1"
  url: "https://vpsie.com/api/v1"
  token: "REDACTED"
