apiVersion: v1
kind: Secret
metadata:
  name: vpsie-secret
  namespace: kube-system
stringData:
  # token: "REDACTED"
  # token: "token-here"
  # token: "REDACTED"
  # token: "REDACTED"
  token: "REDACTED"
  url: "https://api.vpsie.com/apps/v2"
  max-retries: "3"
