apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: vpsie.csi.vpsie.com
spec:
  attachRequired: true
  podInfoOnMount: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vpsie-fast-block-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: ssd
provisioner: vpsie.csi.vpsie.com
allowVolumeExpansion: true


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vpsie-slow-block-storage
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: sata
provisioner: vpsie.csi.vpsie.com
allowVolumeExpansion: true
---

kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: vpsie-fast-block-storage
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: vpsie.csi.vpsie.com
deletionPolicy: Delete

---
# write deployment for controller
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-vpsie-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vpsie-csi-driver
spec: 
  serviceName: "csi-vpsie"
  replicas: 1
  selector:
    matchLabels:
      app: csi-vpsie-controller 
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: csi-vpsie-plugin
      labels:
        app: csi-vpsie-controller
        role: csi-vpsie
    spec:
      priorityClassName: system-cluster-critical
      serviceAccount: csi-vpsie-controller-sa
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--default-fstype=ext4"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.7.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS     
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-vpsie-plugin
          image: natnaeldocker/csi-vpsie:snap
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--url=$(URL)"
            - "--token=$(TOKEN)"
            - "--max-retries=$(MAX_RETRIES)"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: token
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: url
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MAX_RETRIES
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: max-retries
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-vpsie-controller-sa
  namespace: kube-system

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: vpsie-csi-node
  namespace: kube-system
spec: 
  selector:
    matchLabels:
      app: vpsie-csi-node
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: csi-vpsie-plugin
      labels:
        app: vpsie-csi-node
        role: vpsie-csi
    spec:
      priorityClassName: system-node-critical
      serviceAccount: vpsie-csi-node-sa
      hostNetwork: true         
      containers:
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.2
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/vpsie.csi.vpsie.com /registration/vpsie.csi.vpsie.com-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/vpsie.csi.vpsie.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "Always"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration/
        - name: csi-vpsie-plugin
          image: natnaeldocker/csi-vpsie:snap
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--url=$(URL)"
            - "--token=$(TOKEN)"
            - "--max-retries=$(MAX_RETRIES)"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: token
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: url
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MAX_RETRIES
              valueFrom:
                secretKeyRef:
                  name: vpsie-secret
                  key: max-retries
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          terminationMessagePath: /tmp/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: dev-dir
              mountPath: /dev
            - name: udev-data
              mountPath: /run/udev
            - name: host-dir
              mountPath: /host
              mountPropagation: Bidirectional
            - mountPath: /sys
              name: sys-dir

            
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/vpsie.csi.vpsie.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: udev-rules-dir
          hostPath:
            path: /etc/udev/rules.d/
        - name: dev-dir
          hostPath:
            path: /dev
            type: Directory
        - name: udev-data
          hostPath:
            path: /run/udev
        - name: host-dir
          hostPath:
            path: /
            type: Directory
        - name: sys-dir
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpsie-csi-node-sa
  namespace: kube-system
  labels:
    api.kubernetes.io/name: vpsie-csi-driver
    
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-provisioner-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: csi-vpsie-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vpsie-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-snapshotter-role
  labels: 
    app.kubernetes.io/name: vpsie-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshots.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshots.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: csi-vpsie-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: vpsie-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vpsie-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-resizer-role
  labels: 
    app.kubernetes.io/name: vpsie-csi-driver
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims/status" ]
    verbs: [ "update", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "list", "watch", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]

--- 

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-resizer-binding
subjects:
  - kind: ServiceAccount
    name: csi-vpsie-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vpsie-resizer-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-attacher-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]  

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vpsie-attacher-binding
subjects:
  - kind: ServiceAccount
    name: csi-vpsie-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vpsie-attacher-role
  apiGroup: rbac.authorization.k8s.io
# node roles

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpsie-csi-node-driver-registrar-role
  namespace: kube-system
  labels:
    api.kubernetes.io/name: vpsie-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpsie-csi-node-driver-registrar-binding
  labels:
    api.kubernetes.io/name: vpsie-csi-driver
subjects:
  - kind: ServiceAccount
    name: vpsie-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: vpsie-csi-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io