apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpsie-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vpsie-slow-block-storage